# Generated by Django 4.2 on 2023-04-29 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_card', '0002_alter_attendance_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlyattendance',
            options={'ordering': ['-timestamp']},
        ),
    ]
