# Generated by Django 4.2 on 2023-04-29 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_card', '0003_alter_monthlyattendance_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyattendance',
            name='is_start_of_day',
            field=models.BooleanField(default=False),
        ),
    ]
