# Generated by Django 4.2 on 2023-05-05 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_card', '0004_monthlyattendance_is_start_of_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
