# Generated by Django 4.2 on 2023-05-05 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_card', '0006_attendance_end_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_check_in', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='start_time',
        ),
    ]
