# Generated by Django 4.2 on 2023-05-06 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_card', '0008_timecard'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='attendance_time',
            field=models.DateTimeField(null=True),
        ),
    ]
